using System.Net;
using SoftPMS.Application.Features.Notifications.Services;
using SoftPMS.Domain.Entities;

namespace SoftPMS.Infrastructure.Services;

public class NotificationEmailTemplateBuilder : INotificationEmailTemplateBuilder
{
    public string BuildNotificationEmailHtml(UserNotification notification, string recipientName, string? details = null)
    {
        var safeRecipient = WebUtility.HtmlEncode(recipientName);
        var safeTitle = WebUtility.HtmlEncode(notification.Title);
        var safeMessage = WebUtility.HtmlEncode(notification.Message);
        var safeType = WebUtility.HtmlEncode(notification.Type.ToString());

        var targetDateRow = notification.TargetDate.HasValue
            ? $@"
            <tr>
                <td style=""padding: 8px 0; color: #64748b; font-size: 14px;"">Target Date:</td>
                <td style=""padding: 8px 0; color: #1e293b; font-weight: 600; font-size: 14px; text-align: right;"">
                    {notification.TargetDate.Value:MMMM dd, yyyy}
                </td>
            </tr>"
            : string.Empty;

        var remainingDaysRow = notification.RemainingDays.HasValue
            ? $@"
            <tr>
                <td style=""padding: 8px 0; color: #64748b; font-size: 14px;"">Remaining Days:</td>
                <td style=""padding: 8px 0; color: #0284c7; font-weight: 600; font-size: 14px; text-align: right;"">
                    {(notification.RemainingDays.Value >= 0 ? $"{notification.RemainingDays.Value} days" : $"{Math.Abs(notification.RemainingDays.Value)} days overdue")}
                </td>
            </tr>"
            : string.Empty;
            
        var detailsBox = "";
        if (!string.IsNullOrWhiteSpace(details))
        {
            var safeDetails = WebUtility.HtmlEncode(details);
            detailsBox = $@"
<div style=""background-color: #fffbeb; border: 1px solid #fde68a; border-left: 4px solid #f59e0b; border-radius: 8px; padding: 16px; margin: 20px 0 0 0; box-shadow: 0 1px 3px rgba(0,0,0,0.05);"">
    <div style=""font-size: 12px; font-weight: 700; color: #d97706; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.5px;"">Details</div>
    <div style=""font-size: 14px; line-height: 1.6; color: #78350f; margin: 0; white-space: pre-wrap;"">{safeDetails}</div>
</div>";
        }

        return $@"
<div style=""font-size: 16px; color: #475569; margin-bottom: 20px;"">Hello <strong>{safeRecipient}</strong>,</div>
<div style=""display: inline-block; background-color: #e0f2fe; color: #0369a1; font-size: 12px; font-weight: 600; padding: 4px 12px; border-radius: 9999px; margin-bottom: 12px;"">{safeType}</div>

<div style=""background-color: #f8fafc; border: 1px solid #e2e8f0; border-left: 4px solid #0284c7; border-radius: 8px; padding: 20px; margin: 20px 0;"">
    <div style=""font-size: 18px; font-weight: 600; color: #0f172a; margin: 0 0 10px 0;"">{safeTitle}</div>
    <div style=""font-size: 15px; line-height: 1.6; color: #334155; margin: 0;"">{safeMessage}</div>

    <table style=""width: 100%; border-collapse: collapse; margin-top: 16px; border-top: 1px dashed #cbd5e1; padding-top: 12px;"">
        {targetDateRow}
        {remainingDaysRow}
    </table>
    {detailsBox}
</div>

<p style=""font-size: 14px; color: #64748b; line-height: 1.5; margin-top: 24px;"">
    This is an automated passive notification generated by the SoftPMS platform according to your organization's monitoring rules.
</p>";
    }

    public string BuildBirthdayCelebrantEmailHtml(string celebrantFirstName)
    {
        var safeFirstName = WebUtility.HtmlEncode(celebrantFirstName);

        return $@"
<div style=""text-align: center;"">
    <div style=""font-size: 54px; margin-bottom: 12px; display: inline-block;"">🎂 🎉 🎈</div>
    <h2 style=""color: #4f46e5; font-size: 24px; font-weight: 800; margin: 0 0 20px 0;"">Happy Birthday, {safeFirstName}!</h2>
    
    <div style=""display: inline-block; background-color: #fdf2f8; color: #db2777; font-size: 13px; font-weight: 700; padding: 6px 16px; border-radius: 9999px; border: 1px solid #fbcfe8; margin-bottom: 20px;"">🌟 Celebrating You Today!</div>
    
    <div style=""background: linear-gradient(180deg, #fdf4ff 0%, #f5f3ff 100%); border: 1px solid #e9d5ff; border-radius: 12px; padding: 28px 24px; margin: 10px 0 28px 0;"">
        <div style=""font-size: 18px; font-weight: 700; color: #6b21a8; margin-bottom: 12px;"">Wishing you an extraordinary year ahead!</div>
        <p style=""font-size: 16px; line-height: 1.7; color: #334155; margin: 0;"">
            On behalf of everyone at SoftPMS, we wish you a very happy birthday filled with joy, health, and memorable celebrations! 
            <br><br>
            Thank you for bringing your dedication, creativity, and great energy to our team every single day. Here's to another wonderful year of success and happiness!
        </p>
    </div>

    <p style=""font-size: 14px; color: #64748b; margin-top: 20px;"">
        Have a wonderful day and enjoy your special celebration! 🥳
    </p>
</div>";
    }

    public string BuildBirthdayColleagueAnnouncementEmailHtml(string celebrantFullName, string recipientName)
    {
        var safeCelebrant = WebUtility.HtmlEncode(celebrantFullName);
        var safeRecipient = WebUtility.HtmlEncode(recipientName);

        return $@"
<div style=""font-size: 16px; color: #475569; margin-bottom: 16px;"">Hello <strong>{safeRecipient}</strong>,</div>
<div style=""display: inline-block; background-color: #f0fdf4; color: #16a34a; font-size: 12px; font-weight: 700; padding: 4px 12px; border-radius: 9999px; border: 1px solid #bbf7d0; margin-bottom: 16px;"">🎂 Team Celebration</div>

<div style=""background-color: #f8fafc; border: 1px solid #e2e8f0; border-left: 4px solid #6366f1; border-radius: 8px; padding: 24px 20px; margin: 16px 0;"">
    <div style=""font-size: 18px; font-weight: 700; color: #1e1b4b; margin: 0 0 10px 0;"">Today is {safeCelebrant}'s Birthday! 🎉</div>
    <p style=""font-size: 15px; line-height: 1.6; color: #334155; margin: 0;"">
        Today is our colleague <strong>{safeCelebrant}</strong>'s special day! 🎈
        <br><br>
        Please take a moment today to reach out, say happy birthday, and share your warmest wishes to make their day extra joyful and memorable!
    </p>
</div>

<p style=""font-size: 14px; color: #64748b; line-height: 1.5; margin-top: 24px;"">
    This is an automated celebratory notification from SoftPMS. Let's celebrate our team together!
</p>";
    }
}
