using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SoftPMS.Domain.Entities;

namespace SoftPMS.Persistence.Configurations;

public class AuditLogConfiguration : IEntityTypeConfiguration<AuditLog>
{
    public void Configure(EntityTypeBuilder<AuditLog> builder)
    {
        builder.ToTable("AuditLogs");

        builder.HasKey(a => a.Id);

        // High-volume surrogate identity key generated by the database
        builder.Property(a => a.Id)
            .ValueGeneratedOnAdd();

        builder.Property(a => a.CorrelationId)
            .IsRequired();

        builder.Property(a => a.TableName)
            .IsRequired()
            .HasMaxLength(100);

        builder.Property(a => a.RecordId)
            .IsRequired()
            .HasMaxLength(256);

        builder.Property(a => a.Action)
            .IsRequired()
            .HasMaxLength(20);

        // JSON delta snapshots stored as unbounded text
        builder.Property(a => a.OldValues)
            .HasColumnType("nvarchar(max)");

        builder.Property(a => a.NewValues)
            .HasColumnType("nvarchar(max)");

        builder.Property(a => a.ChangedByUserId)
            .HasMaxLength(100);

        builder.Property(a => a.ChangedByEmail)
            .IsRequired()
            .HasMaxLength(100);

        builder.Property(a => a.ChangedAt)
            .IsRequired();

        // 1. Heavy transaction / correlation tracing index
        builder.HasIndex(a => a.CorrelationId)
            .HasDatabaseName("IX_AuditLogs_CorrelationId");

        // 2. Index for querying the complete lifecycle history of a specific table record
        builder.HasIndex(a => new { a.TableName, a.RecordId })
            .HasDatabaseName("IX_AuditLogs_TableName_RecordId");

        // 3. Index for querying changes made by a specific user ID
        builder.HasIndex(a => a.ChangedByUserId)
            .HasDatabaseName("IX_AuditLogs_ChangedByUserId");

        // 4. Index for querying changes made by a specific user email
        builder.HasIndex(a => a.ChangedByEmail)
            .HasDatabaseName("IX_AuditLogs_ChangedByEmail");

        // 5. Index for chronological timeline and date-range queries
        builder.HasIndex(a => a.ChangedAt)
            .HasDatabaseName("IX_AuditLogs_ChangedAt");
    }
}
